name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Grant write permissions to the GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Set up Node.js (for Allure CLI and other dependencies)
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Ensuring compatibility with Node.js 20

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress

      - name: Ensure browsers are installed
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

      - name: Run tests
        run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' mvn test
        env:
          CI: true

      - name: Verify Allure Results Directory
        run: ls -R target/allure-results
        # Listing files in the allure-results to ensure data is generated correctly

      - name: Generate Allure Report
        run: allure generate target/allure-results --clean -o allure-report

      - name: Verify Allure Report Directory
        run: ls -R allure-report
        # Listing files in the allure-report to ensure report is generated correctly

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4  # Update to v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: ${{ github.event_name == 'push' }} # Only deploy on push events
        uses: peaceiris/actions-gh-pages@v4  # Update to v4 to ensure compatibility with Node.js 20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report