name: Playwright Tests

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch: # Add manual trigger

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    permissions:
      contents: write # Grant write permissions to the GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff1 \
            libopus0 \
            libvpx7 \
            libevent-2.1-7 \
            libgstreamer-plugins-base1.0-0 \
            libgstreamer1.0-0 \
            libgstreamer-plugins-good1.0-0 \
            libgstreamer-gl1.0-0 \
            libgstreamer-plugins-bad1.0-0 \
            gstreamer1.0-libav \
            gstreamer1.0-gl \
            gstreamer1.0-gtk3 \
            gstreamer1.0-pulseaudio \
            gstreamer1.0-tools \
            gstreamer1.0-x \
            libharfbuzz-icu0 \
            libhyphen0 \
            libgles2-mesa \
            libx264-dev \
            flite1-dev \
            libgstreamer-plugins-bad1.0-0 \
            libmanette-0.2-0 \
            libsndio-dev

      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Set up Node.js (for Allure CLI and other dependencies)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress

      - name: Ensure browsers are installed
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Create Allure Environment and Executor Files
        run: |
          mkdir -p allure-results
          
          # Create environment.properties file dynamically
          echo "OS=$(uname -s)" >> allure-results/environment.properties
          echo "Java Version=$(java -version 2>&1 | awk -F '\"' '/version/ {print $2}')" >> allure-results/environment.properties

          # Dynamic Browser Version
          BROWSER_NAME=$(mvn exec:java -Dexec.mainClass='Utils.AllureEnvironmentWriter' -Dexec.args="browserName" -q)
          BROWSER_VERSION=""
          if [ -z "$BROWSER_NAME" ]; then
            echo "Warning: Browser name is empty. Cannot detect browser version."
          else
            case "$BROWSER_NAME" in
              "chromium")  
                BROWSER_VERSION=$(google-chrome --version | awk '{print $3}') 
                ;;
              "firefox")   
                BROWSER_VERSION=$(firefox --version | head -1 | awk '{print $3}')  
                ;;
              "webkit")    
                BROWSER_VERSION=$(jsc --version 2>&1 | head -1 | awk '{print $4}')
                ;; # Assuming JavaScriptCore for simplicity 
              *)           
                echo "Warning: Unsupported browser '$BROWSER_NAME'. Version detection might fail."
                ;;
            esac
            echo "Browser Version=${BROWSER_VERSION}" >> allure-results/environment.properties
          fi
          
          # Create executor.json file dynamically
          cat <<EOF > allure-results/executor.json
          {
            "name": "GitHub Actions",
            "type": "github",
            "url": "https://github.com/${{ github.repository }}",
            "buildOrder": "${{ github.run_id }}",
            "buildName": "${{ github.run_number }}",
            "buildUrl": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "reportUrl": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "reportName": "Allure Report - GitHub Actions"
          }
          EOF

      - name: Run tests
        run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' mvn test || true
        env:
          CI: true

      - name: Verify Allure Results Directory
        run: |
          if [ -d "allure-results" ]; then
            echo "Allure results directory exists"
            ls -R allure-results
          else
            echo "Allure results directory does not exist"
            exit 1
          fi

      - name: Verify Allure Environment and Executor Files
        run: |
          if [ -f "allure-results/environment.properties" ]; then
            echo "environment.properties file exists"
          else
            echo "environment.properties file does not exist"
            exit 1
          fi
          if [ -f "allure-results/executor.json" ]; then
            echo "executor.json file exists"
          else
            echo "executor.json file does not exist"
            exit 1
          fi

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Verify Allure Report Directory
        run: |
          if [ -d "allure-report" ]; then
            echo "Allure report directory exists"
            ls -R allure-report
          else
            echo "Allure report directory does not exist"
            exit 1
          fi

      - name: Deploy Allure Report to GitHub Pages
        if: ${{ github.event_name == 'push' }} # Only deploy on push events
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: allure-report
          publish_branch: gh-pages
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com